### ISSUE TITLE
Module Not Compatible with 13.2

### ISSUE THREAD

**Issue by mravily** [red5pro/terraform-aws-red5pro#22]
## Description

The module is not compatible with the latest version of the Red5Pro Server 13.2 and AWS controller 12.5.0, during the creation of node group, it stay in initialiazing state, that block the creation of other ressource.

```
GET http://${SM_IP}:5080/streammanager/api/4.0/admin/nodegroup
[
	{
		"id": 1,
		"name": "terraform-node-group",
		"originConnections": 0,
		"regions": [
			"eu-west-3"
		],
		"launchConfig": "red5pro-auto-launch-config-oe-1735128265",
		"scalePolicy": "red5pro-auto-scale-policy-1o-1e-1735128265",
		"state": "initializing",
		"timestamp": 1735128276142
	}
]
```

During my investigate, i extract the contents of server zip, i've noticed the conf/autoscale.xml doesn't contain the  `<property name="cloudWatchHost" ... \>`  describe in the [troubleshooting documentation](https://www.red5.net/docs/troubleshooting/auto-install-troubleshooting/general-auto-troubleshooting/#NodegroupDoesntPopulate) and use [r5p_config_node.sh](https://github.com/red5pro/terraform-aws-red5pro/blob/1.1.12/red5pro-installer/r5p_config_node.sh#L48). I tried to add manually the property section into the file, but it seems not supported by the version 13.2.

```
2024-12-25 12:58:36,227 [pool-5-thread-2] INFO  com.red5pro.clustering.autoscale.AutoScale - AutoScalePlugin start
2024-12-25 12:58:36,256 [pool-5-thread-2] INFO  com.red5pro.clustering.autoscale.AutoScale - Exception setting defaults
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'config' defined in file [/usr/local/red5pro/conf/autoscale.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'cloudWatchHost' of bean class [com.red5pro.clustering.autoscale.Configuration]: Bean property 'cloudWatchHost' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1744)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:209)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:142)
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:121)
        at com.red5pro.clustering.autoscale.AutoScale.doStartProPlugin(Unknown Source)
        at com.red5pro.activation.ProPluginator.a(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'cloudWatchHost' of bean class [com.red5pro.clustering.autoscale.Configuration]: Bean property 'cloudWatchHost' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
        at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:243)
        at org.springframework.beans.AbstractNestablePropertyAccessor.processLocalProperty(AbstractNestablePropertyAccessor.java:432)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:278)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:266)
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:104)
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:79)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1740)
        ... 20 common frames omitted
2024-12-25 12:58:36,259 [pool-5-thread-2] DEBUG com.red5pro.clustering.autoscale.AutoScale - done
2024-12-25 12:58:36,259 [pool-5-thread-2] INFO  com.red5pro.plugin.Red5ProPlugin - Dispatch server event: java.beans.PropertyChangeEvent[propertyName=PLUGIN_START; oldValue=null; newValue=Red5Pro-Cloudstorage; propagationId=null; source=com.red5pro.media.storage.CloudstoragePlugin@20be85b5]
```

I rollback on the Red5Pro Server 12.4, and it's work perfectly with the module version 1.1.12.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version 1.1.12:

- Terraform version:
 ```
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.68.0
+ provider registry.terraform.io/hashicorp/local v2.5.2
+ provider registry.terraform.io/hashicorp/null v3.2.3
+ provider registry.terraform.io/hashicorp/tls v4.0.6
```
## Reproduction Code

Use the module with Red5Pro Server 13.2.0 and AWS Cloud Controller 12.5.0

```
module "red5pro" {
  source = "red5pro/red5pro/aws"
  version = "1.1.12"

  type = "cluster"        # Deployment type: single, cluster, autoscaling
  name = var.red5pro.name # Name to be used on all the resources as identifier

  ubuntu_version               = "22.04"                                      # Ubuntu version for Red5 Pro servers
  path_to_red5pro_build        = "./packages/red5pro-server-13.2.0.zip"       # Absolute path or relative path to Red5 Pro server ZIP file
  path_to_aws_cloud_controller = "./packages/aws-cloud-controller-12.5.0.jar" # Absolute path or relative path to AWS Cloud Controller JAR file
  [...]
```

## Expected behavior

Deploy entire ressources with the last version of Red5Pro Server

## Actual behavior

Block during the creation of node group

### Terminal Output Screenshot(s)

![Screenshot 2024-12-25 at 01 20 28](https://github.com/user-attachments/assets/602198ce-acfe-4aef-a0c3-b40ce3643c68)

**Comment by iolesyk** [comment]
Hi,

The latest Red5 Pro server builds (13.0.0 and above) are compatible only with Stream Manager 2.0. As a result, we have been updating the Terraform module to support Stream Manager 2.0 alongside these newer server builds.

I’m pleased to inform you that the update is now complete and currently undergoing QA testing. We anticipate releasing it soon.

Thank you for your patience and support.

**Comment by mravily** [comment]
Hi,
What a great new !
Thanks for your answer
